name: Test Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Action
        uses: ./
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: 'leaderboard bar pie donut'
          output_path: 'stats'
          exclude_languages: 'HTML,CSS'
          top_repos_count: '5'
          commit_message: 'Update language statistics [skip ci]'
